language: node_js
node_js:
  - stable
  - '4.1'
  - '4.0'

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#metabrainz"
    on_success: always
    on_failure: always
    template:
      - "Project %{repository_name} build #%{build_number}: %{result} in %{elapsed_time}: %{build_url}"

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - git clone https://github.com/bookbrainz/bookbrainz-sql.git
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz; CREATE SCHEMA bookbrainz;' -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/musicbrainz.sql -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/bookbrainz.sql -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/scripts/create_triggers.sql -d bookbrainz_test -U postgres
  - cp ./config/test.json.example ./config/test.json

script:
  - npm run-script test-ci

after_script:
  - npm install -g coveralls && coveralls < coverage/lcov.info
