version: '3'

services:

  bookbrainz-site:
    container_name: bookbrainz-site
    command: npm start
    build:
      context: .
    restart: unless-stopped
    ports:
      - "9099:9099"
  
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:9.5
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:3.2-alpine
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
      - "3600:3600"

volumes:
  postgres-data:
