version: '3'

services:

  bookbrainz-site:
    container_name: bookbrainz-site
    command: npm start
    build: ./
    restart: unless-stopped
    ports:
      - "9099:9099"
    depends_on:
      - elasticsearch
      - redis
      - postgres
  
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:9.5
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      # Skip bootstrap checks (see https://github.com/docker-library/elasticsearch/issues/98)
      - transport.host=127.0.0.1
      - discovery.zen.minimum_master_nodes=1
    ports:
      - "9200:9200"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:3.2-alpine
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
      - "3600:3600"

  startup:
    image: waisbrot/wait
    container_name: startup
    environment:
      - TARGETS=redis:6379,postgres:5432,elasticsearch:9200
    depends_on:
      - elasticsearch
      - redis
      - postgres

volumes:
  postgres-data:
